wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.2
    start_time: 1664865434
    t:
      1:
      - 1
      - 5
      - 35
      - 53
      - 55
      - 77
      3:
      - 16
      4: 3.10.2
      5: 0.12.21
      8:
      - 3
      - 5
dropout_probability:
  desc: null
  value: 0.5
h_channel:
  desc: null
  value: 512
lr:
  desc: null
  value: 0.0014906194358531772
number_conv_layers:
  desc: null
  value: 4
trial.number:
  desc: null
  value: 0
